defaults: &defaults
  working_directory: ~/buildbox
  docker:
    - image: circleci/ruby:2.5.3-node-browsers-legacy
      environment:
        BUNDLE_JOBS: 3
        BUNDLE_RETRY: 3
        BUNDLE_PATH: vendor/bundle
        RAILS_ENV: test
        RACK_ENV: test

version: 2.0
jobs:
  test:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
          - buildbox-{{ checksum "Gemfile.lock" }}

      - run:
          name: Run bundle install
          command: bundle check || bundle install

      # Run and debug unit tests right here

      - save_cache:
          key: buildbox-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/buildbox/vendor/bundle

  build:
    <<: *defaults
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run: 
          name: Build and push images to Docker Registry
          command: |
            DEPLOY_TAG=${CIRCLE_BUILD_NUM}.${CIRCLE_SHA1:0:7}

            docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}

            docker tag buildbox_rails tanngoc93/${DEPLOY_APP_NAME}:${DEPLOY_TAG}
            docker tag buildbox_nginx tanngoc93/${DEPLOY_SERVER_NAME}:${DEPLOY_TAG}

            docker push tanngoc93/${DEPLOY_APP_NAME}:${DEPLOY_TAG}
            docker push tanngoc93/${DEPLOY_SERVER_NAME}:${DEPLOY_TAG}

workflows:
  version: 2
  Build-and-Deploy:
    jobs:
      - test
      - build:
          requires:
            - test
          filters:
            branches:
              only: master